#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

YABAI_MAX_SPACES=8

# Enforce the number of spaces regardless of the number of displays
# also reapply the rules
yabai -m signal --add event=display_added action="~/.config/yabai/destroy_excess_spaces.zsh $YABAI_MAX_SPACES"
yabai -m signal --add event=display_added action="sleep 1; find ~/.config/yabai/yabai.rules -type f -perm +111 -exec {} \;"

yabai -m signal --add event=display_removed action="yabai -m space --create"
yabai -m signal --add event=display_removed action="sleep 1; find ~/.config/yabai/yabai.rules -type f -perm +111 -exec {} \;"

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  1
yabai -m config bottom_padding               1
yabai -m config left_padding                 1
yabai -m config right_padding                1
yabai -m config window_gap                   2

# Run rules
find ~/.config/yabai/yabai.rules -type f -perm +111 -exec {} \;
